### ISSUE TITLE
Storing Data on an External Drive

### ISSUE THREAD

**Issue by xKekistanx** [yep/virtualOS#1]
Hi all,
I'm running a 2021 MBA M1 8C 8GB with 256GB of storage
Would it be possible to store the files downloaded on an external drive? I don't have the capacity left to store them on my local drive.
Thanks!

**Comment by zanza89** [comment]
Hi all,

it doesn't work for me running on MBP 16" 2021 M1 Max 64GB 2TB of storage. I can't get to the initial OS setup.  Anybody has the same issue?

**Comment by yep** [comment]
Yes, I agree that adding an option to set the location of the virtual machine would be nice.

Apps distributed using Apple's AppStore have to adopt [App Sandbox](https://developer.apple.com/documentation/security/app_sandbox), which by default limits the file system locations the app can access. Thus, using one of the options described in [App Sandbox Guide](https://developer.apple.com/library/archive/documentation/Security/Conceptual/AppSandboxDesignGuide/AboutAppSandbox/AboutAppSandbox.html#//apple_ref/doc/uid/TP40011183-CH1-SW1) in section "Powerbox and File System Access Outside of Your Container" is required to lift the file system restriction for this feature.

**Comment by yep** [comment]
It's possible to set the hard disk location in settings now.
