### ISSUE TITLE
where is the data stored ?

### ISSUE THREAD

**Issue by leonvita91** [yep/virtualOS#11]
I had installed this app and I don't know what happened where this data stored and what happened in the background which is not good app, so now I want to delete everything this app download it.
may you show me where is this data stored because I searched everywhere and I couldn't find this data.

**Comment by yep** [comment]
Virtual machine bundles and restore images are stored here:
 - In Finder, in the "Go" menu, select "Go to Folder..." (Or press `command-shift-g`)
 - Go to this folder: `~/Library/Containers/com.github.yep.ios.virtualOS/Data`

**Comment by yep** [comment]
Also, you can delete the files created by the app from the file menu: It's at
`File -> Delete Restore Image`
 and
`File -> Delete Virtual Machine`

**Comment by yep** [comment]
Version 1.1 displays the exact storage location in the settings window.
