### ISSUE TITLE
Failed to read virtual machine from disk

### ISSUE THREAD

**Issue by jeromectm** [yep/virtualOS#12]
I updated to version 1.1 and now get this error; I did not try to change the disk image size (yet). Hope I won't have lost everything in this drive!

**Comment by yep** [comment]
VM storage location changed from
 
 - `~/Library/Containers/com.github.yep.ios.virtualOS/Data/virtualOS.bundle` in version 1.0 to 
 - `~/Library/Containers/com.github.yep.ios.virtualOS/Data/Documents/virtualOS.bundle` in version 1.1
 
 as the `Documents` directory contains less unrelated files (~ is the path to you home/user directory).

The VM (`virtualOS.bundle`) should be moved to the new location automatically on app start. Maybe it was not moved automatically in your case for some reason? If you move it to the new location manually, it should be found by the app again.

Changing the disk image size only has effect before install and thus should be safe thereafter.

**Comment by jeromectm** [comment]
I tried again after some time (and after having rebooted) and then it worked fine.
Is there some way to resize an existing image (disk utility, command line…)? Is there some possibility to use a sparse disk image? Or maybe with APFS, space allocated to the disk image is not actually used until some data is written? Thanks!

**Comment by yep** [comment]
> I tried again after some time (and after having rebooted) and then it worked fine.

Glad it's working now.

> Is there some way to resize an existing image (disk utility, command line…)

None I am aware of. If anybody reading this knows more, please add a comment.

> Is there some possibility to use a sparse disk image? Or maybe with APFS, space allocated to the disk image is not actually used until some data is written? 

Again, I do not know if this is possible.
