### ISSUE TITLE
Cannot connect to wifi

### ISSUE THREAD

**Issue by hecker1230** [yep/virtualOS#13]
I can't connect to wifi network and Ethernet doesn't work also so plz can u help me ?
<img width="1440" alt="Screen Shot 2022-08-02 at 13 43 23" src="https://user-images.githubusercontent.com/110428399/182379653-181084a9-af41-4ba2-81a7-bff55f9cbf4d.png">
<img width="1440" alt="Screen Shot 2022-08-02 at 13 55 04" src="https://user-images.githubusercontent.com/110428399/182379744-7b5749a0-80e6-4c9c-a1b7-b9e0a75335ef.png">

**Comment by 4x10m** [comment]
Can't connect to internet too :/

**Comment by WilsonApexive** [comment]
Internet works for me on M1 Mac running 14.1.1.

**Comment by Chrno21** [comment]
Also unable to connect to Network...
Apple M2 Max
14.4.1

**Comment by yep** [comment]
You can only use the internet connection provided by the host, I think.
