### ISSUE TITLE
Sign in to iCloud fails

### ISSUE THREAD

**Issue by backpacked** [yep/virtualOS#21]
When signing into iCloud from System Preferences fails with Authentication failed. Seems like this is a problem with all VMs out there. Hope you can find a solution.

**Comment by ArcCal** [comment]
cannot sign in  Apple ID in iCloud and app store: This action cannot  be completed

**Comment by PaoloSupino** [comment]
I'm having the same problem...

**Comment by saiedg** [comment]
Any fix for this?

**Comment by yep** [comment]
Any errors occurring inside the VM are out of scope of this project.

**Comment by yep** [comment]
Maybe this helps: https://developer.apple.com/documentation/virtualization/using_icloud_with_macos_virtual_machines

**Comment by JLWLL** [comment]
> Maybe this helps: https://developer.apple.com/documentation/virtualization/using_icloud_with_macos_virtual_machines
> 
> iCloud appears to require a macOS 15 guest.

Yes.But APP STORE still can not use. 

Where can I find some way to solve this problem?
