### ISSUE TITLE
launch at startup

### ISSUE THREAD

**Issue by alexcohn** [yep/virtualOS#22]
I would like to start the virtual machine automatically when the host boots. This means, _a)_ to start the **virtualOS** application, and _b)_ to start the (preconfigured) macOS from it. Is this possible? Is this possible without modifying and rebuilding the app?

**Comment by ArcCal** [comment]
I need this feature, too.

**Comment by yep** [comment]
Thanks for adding this feature!
Merged https://github.com/yep/virtualOS/pull/23, created a new TestFlight beta (use https://testflight.apple.com/join/vWKNYgmM to join the beta) and uploaded version 1.2.1 containing this feature to the Apple AppStore.

Starting the virtualOS app when the machine boots should be possible like this:
https://support.apple.com/de-de/guide/mac-help/mh15189/mac

If it's not possible to pass the `--args start` argument when opening the app on boot/login, it is also possible add a checkbox for starting the VM when the app is opened to the settings window.
