### ISSUE TITLE
Installation fails on macos 13.3.1

### ISSUE THREAD

**Issue by flavingl** [yep/virtualOS#27]
I'm trying installing a virtual macOS via virtualOS on MacBookPro M1 runnig macos 13.3.1 and I always get the error attached

It happens whatever .ipsw I try.

<img width="1511" alt="Screenshot 2023-05-11 alle 12 05 03" src="https://github.com/yep/virtualOS/assets/133215542/243ee4ee-a2e4-439d-b01a-3a817275611e">

**Comment by WilsonApexive** [comment]
virtualOS automatically downloaded and installed 14.1.1 for me. I didn't need to manually download a .ipsw.
