### ISSUE TITLE
Where does the system image saved ?

### ISSUE THREAD

**Issue by SKbarbon** [yep/virtualOS#29]
Where does the system image saved ?

I hope in the app container. So when the app deleted all its files being deleted

**Comment by sinarf** [comment]
I found it here:
`~/Library/Containers/com.github.yep.ios.virtualOS/Data/Documents`

The default value is set here: https://github.com/yep/virtualOS/blob/main/virtualOS/Extension/URL%2BPaths.swift

And hopefully it is NOT deleted when you uninstall the application because that would be very bad.

**Comment by yep** [comment]
Yes, by default, all data is stored at `~/Library/Containers/com.github.yep.ios.virtualOS/Data/Documents`
Data in that directory is not removed when the app is deleted.
