### ISSUE TITLE
Photos app crashes when viewing pictures or video

### ISSUE THREAD

**Issue by Marcus1068** [yep/virtualOS#3]
hi, thx for the great app! Anyways after importing photos or videos in the stock photos app the app crashes when viewing those after double click.

**Comment by yep** [comment]
Everything happening inside the virtual machine is somewhat out of the scope of this project, as it uses Apple's [Virtualization Framework](https://developer.apple.com/documentation/virtualization/virtualize_macos_on_a_mac) at the core.

I propose you create an account at the Apple [developer forum](https://developers.apple.com/forums/) and ask there. Chances are that an Apple Engineer can provide additional information.
