### ISSUE TITLE
OSX 14.0

### ISSUE THREAD

**Issue by Gyrinx** [yep/virtualOS#31]
See the VirtualOS.bundle, can't open or start it with VirtualOS. OSX Version 14. Maybe the container has changed.

**Comment by yep** [comment]
Sorry, I can not reproduce this issue. macOS 14 (Sonoma) is running fine for me. Maybe try to re-install the VM by deleting the current VM and restore image: in the menu -> File -> Delete Virtual Machine and -> File -> Delete Restore Image

**Comment by WilsonApexive** [comment]
Working for me with 14.1.1

**Comment by kapsolas** [comment]
Mine was working as well. Had to reboot and it goes into recovery mode now.
It doesn't seem to find the drive anymore.
