### ISSUE TITLE
Unknown error login ID Apple 

### ISSUE THREAD

**Issue by vittorioPiotti** [yep/virtualOS#33]
Hi the service is fantastic💪. I only have a problem with using my apple id in virtual OS as I get an unknown error. I don't know if it's my problem or if it's a bug or if you just can't use the apple id in a virtual machine. I hope for an answer and thank you in advance

**Comment by lubomben** [comment]
You can't use AppleID in virtual machines. It happens also with Parallel Desktop.

**Comment by secretagencyit** [comment]
...So... how can you install apps onto the VM from the AppStore?

**Comment by lubomben** [comment]
You can't. Any virtualization app can do it. It's a limitation of Apple virtualisation framework. You must find the relative app to download maybe on the releaser website.

**Comment by secretagencyit** [comment]
You can try downloading and installing apps from the AppStore on your host machine and then copying them into the shared folder of your guest.   That worked for me for one app. Not sure all apps will work that way.

**Comment by simsherpa** [comment]
Does this mean that the VM does not support Apple apps that require appleid login? For example Xcode to connect to AppStore connect?
