### ISSUE TITLE
Transfer files from real machine

### ISSUE THREAD

**Issue by smanookian** [yep/virtualOS#35]
There is no possibility to transfer files from my real mac to virtualOS

**Comment by secretagencyit** [comment]
This! Was hoping we could drag and drop from Host to guest and vice versa.

**Comment by yep** [comment]
You can try to set up a shared folder to transfer files between VM and host.

**Comment by secretagencyit** [comment]
Ah, yes, that worked. Thanks!

**Comment by stu2019** [comment]
Trying to select a custom shared folder throws the error Failed to open auxiliary storage on Mac OS 14.5, see screenshot.
<img width="894" alt="Bildschirmfoto 2024-06-02 um 13 55 18" src="https://github.com/yep/virtualOS/assets/49641522/ad175a88-7b54-42eb-ba36-55d6bf15fd80">
Also it does not remember if I try to switch back to no shared folder, virtual is try always to open the custom folder. Where can I find the preference file?

**Comment by yep** [comment]
Please create a separate issue for the unrelated auxiliary storage issue.
