### ISSUE TITLE
USB does not work

### ISSUE THREAD

**Issue by secretagencyit** [yep/virtualOS#37]
Thanks for this great, free resource! 

Is it possible to use USB devices in the guest OS? 

Mine is not seeing my MIDI controller. 

Thanks!

**Comment by secretagencyit** [comment]
Oh, looks like a limitation of Apple’s Virtualization Framework. Never mind.

**Comment by t0kieu** [comment]
Probably situation was changed https://developer.apple.com/documentation/virtualization/usb_devices
