### ISSUE TITLE
It can't start in recovery mode

### ISSUE THREAD

**Issue by pcha** [yep/virtualOS#38]
I'm trying to start machine in recovery mode but i'm not able to do it.
These is my computer configuration:
![Screenshot 2024-06-01 at 18 37 48](https://github.com/yep/virtualOS/assets/10269965/f14b86b6-d7c0-4b72-b49d-0eede60416fc)

I tried restarting and pressing cmd+R but it doesn't happen. The other option to start in recovery mode, scpecifically for M1 macs is keeping pressed the turn on buttom, wicho obviously isn't an option in the virtual machine.

Thanks a lot.

**Comment by yep** [comment]
Please have a look at https://github.com/insidegui/VirtualBuddy
