### ISSUE TITLE
Cannot open menus during the download

### ISSUE THREAD

**Issue by fumoboy007** [yep/virtualOS#5]
While a restore image is being downloaded, when I try to open a menu, the menu opens briefly and then is closed automatically. Perhaps something related to SwiftUI updates of the download progress text?

**Comment by tuxtof** [comment]
same here

**Comment by yep** [comment]
This should be fixed in the beta of version 1.1

You can sign up for the beta here:
https://testflight.apple.com/join/vWKNYgmM

**Comment by yep** [comment]
Closing, please re-open if the issue persists in version 1.1
