### ISSUE TITLE
at-sign is on wrong key - it is not on option-l - it's on option-q

### ISSUE THREAD

**Issue by gentschi** [yep/virtualOS#7]
at-sign is on wrong key - it is not on option-l - it's on option-q

**Comment by yep** [comment]
Sorry, I can not reproduce this issue. For me, the @ sign is on Option-L

**Comment by gentschi** [comment]
my host os is monterey 12.4 and my guest os is ventura 13 developer preview

**Comment by yep** [comment]
To narrow down possible sources of this error, could you please provide additional information:
 - What is your physical keyboard layout/language?
 - What is your host's and guest's keyboard language? -> Settings -> Keyboard -> Text Input
 - What is your host's and guest's system language? -> Settings -> General -> Language & Region -> Preferred Languages -> Primary

Related: #32

**Comment by gentschi** [comment]
Problem is solved. The default keyboard layout was not correct. It was not "German - QWERTZ" ("Deutsch - QWERTZ"), it was "German -default" ("Deutsch - Standard") and on this the @ is alt-Q and not alt-L.

**Comment by yep** [comment]
Great, thanks for reporting back. I'll close the issue then.
