### ISSUE TITLE
Unable to use the Apps - stay blocked 

### ISSUE THREAD

**Issue by tuxtof** [yep/virtualOS#8]
I just try to install the apps on my machine

Mac Studio 2022
Apple M1 Max
Ram 64GB

macOS 12.4

at the first launch I get the same error as #2 

I try to delete everything and restart

after the download of the restore image, I stay blocked at the following windows

![image](https://user-images.githubusercontent.com/180613/173175742-97656edd-4418-4abb-b11f-c124f2855913.png)

is there a way to get more log ??

**Comment by yep** [comment]
In the beta build of version 1.1, the logging that was previously only available when running in debug mode using Xcode, is written to the system log.
That means you can use [Konsole](https://support.apple.com/guide/console/welcome/mac) to filter for `virtualOS` and see additional information.

The beta version is available here: https://testflight.apple.com/join/vWKNYgmM

In the beta version, the storage location of the virtual machine file is shown in the settings. You could try to delete both the `RestoreImage.ipsw` and `virtualOS.bundle` to start over.
