### ISSUE TITLE
Keyboard mapping issue

### ISSUE THREAD

**Issue by ybizeul** [yep/virtualOS#9]
I own a French Apple Magic Keyboard with touch ID and number pad , not sure that's relevant, but anyways :

![image](https://user-images.githubusercontent.com/182035/173176429-870bdf50-8ce4-4962-bb01-3a343e5bfe63.png)

I cannot type characters like "@" that's on the upper left hand corner of the physical keyboard.

**Comment by mackoj** [comment]
I have the same issue I did change the keyboard to ABC and type 2.

**Comment by yep** [comment]
Please try the solution described in https://github.com/yep/virtualOS/issues/32#issuecomment-1837281615
